# Default values for demo-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# Dependency values
demo-frontend:
  enabeld: true
demo-backend:
  enabeld: true
