apiVersion: v2
appVersion: 0.3.1
description: A Helm chart for Kubernetes
name: demo-backend
type: application
version: 0.3.1
maintainers:
  - name: hegerdes
    email: hegerdes@outlook.de
    url: https://henrikgerdes.me
