name: Build Container Images

on:
  push:
    branches: [main, master]
    paths: ['frontend/**', 'backend/**']

jobs:
  build-image:
    strategy:
      matrix:
        app: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.version }}
          push: true
          sbom: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-app-flask-nuxt:${{ matrix.version }}
