name: Build Container Images

on:
  push:
    branches: [main, master]
    paths: ['frontend/**', 'backend/**']

jobs:
  build-image:
    strategy:
      matrix:
        app: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set tag env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          sbom: true
          context: ${{ matrix.version }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-app-flask-nuxt:${{ matrix.version }}
          build-args: |
            APP_VERSION=${{ env.RELEASE_VERSION }}
            COMMIT_HASH=${{ env.SHORT_SHA }}
          labels: |
            REPO=${{ env.GITHUB_REPOSITORY }}
            MAINTAINER=info@example.com
