name: Build Container Images

on:
  push:
    branches: [main]
    paths: ['frontend/**', 'backend/**']
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  docker-build:
    strategy:
      matrix:
        app: [backend, frontend]
    uses: hegerdes/publish/.github/workflows/reusable-docker-build.yml@main
    with:
      build-context: ${{ matrix.app }}
      build-tags: ${{ github.actor }}/demo-app-flask-nuxt:${{ matrix.app }}
      build-cache: type=gha
      build-args: COMMIT_HASH=${{ github.sha }},APP_VERSION=${{ github.ref_name }}
      build-labels: MAINTAINER=${{ github.actor }},REPO=${{ github.repository }}
      build-platforms: linux/amd64,linux/arm64
      extra-command: echo 'Checkout my website henrikgerdes.me'
      push: ${{ github.ref_name == 'main' }}
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      REGISTRY_PW: ${{ secrets.DOCKERHUB_TOKEN }}
      # COSIGN_KEY_STORE: ${{ secrets.COSIGN_PVT_KEY }}
