name: Release Charts

on:
  push:
    branches: [main, master]

jobs:
  Release-Charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package Charts
        run: |
          mkdir -p charts/.deploy
          helm package charts/demo-backend/ --version 0.2.0 --app-version 0.2.0 --destination charts/.deploy
          helm package charts/demo-frontend/ --version 0.2.0 --app-version 0.2.0 --destination charts/.deploy

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
